[bindings]
North = "Triangle"
East = "Circle"
LeftTrigger = "L1"
RightTrigger = "R1"
Select = "Select"
Start = "Start"
South = "Cross"
LeftTrigger2 = "L2"
West = "Square"
RightTrigger2 = "R2"
DPadUp = "DUp"
DPadDown = "DDown"
DPadLeft = "DLeft"
DPadRight = "DRight"
