[bindings]
E = "L2"
Q = "L1"
ArrowLeft = "DLeft"
ArrowRight = "DRight"
S = "Triangle"
ArrowDown = "DDown"
Z = "Cross"
ArrowUp = "DUp"
W = "R1"
R = "R2"
Enter = "Start"
A = "Square"
Backspace = "Select"
X = "Circle"
